# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  auth0_id: <%= ENV['AUTH0_ID'] %>
  auth0_secret: <%= ENV['AUTH0_SECRET'] %>
  auth0_domain: <%= ENV['AUTH0_DOMAIN'] %>

development:
  <<: *default
  secret_key_base: da48a154310bbb2dfcafc2f58b75d50deedd70007cfca322e23be52c754117521243acffde4782cbe9b56dd7954ccd2700fd9f34494eb8c7e02cd74a9f1005b6

test:
  <<: *default
  secret_key_base: 189a2a203a2bb0a346cc4ce95cb79bbf08f06ad1b1f56534337aa078a554569ec41bfe5d54619b30bfd8e8cd159a13e2739ba8f47ded2dd662b68b5b68db788f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
